output:
  format: line-number

linters:
  disable-all: true
  enable:
    - asasalint
    - bodyclose
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - gofmt
    - gofumpt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nilerr
    - nolintlint
    - predeclared
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unused

linters-settings:
  goimports:
    local-prefixes: "github.com/nerdswords/yet-another-cloudwatch-exporter"
