before:
  hooks:
    - dep ensure
builds:
- binary: yace
  goarch:
    - amd64
  env:
  - CGO_ENABLED=0
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    amd64: x86_64
  files:
  - none*
checksum:
  name_template: 'checksums.txt'
