version: '2'
services:
  app:
    build:
      context: .
      dockerfile: /Dockerfile-build-binaries
    working_dir: /go/src/app
    volumes:
      - ./:/copy
    command:
      - cp /root/yace-linux-amd64 /copy; cp /root/yace-darwin-amd64 /copy
