FROM golang:1.10 as builder

RUN curl -fsSL -o /usr/local/bin/dep https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 && chmod +x /usr/local/bin/dep

WORKDIR /go/src/yace
ADD ./src/Gopkg.lock ./src/Gopkg.toml ./
RUN dep ensure -vendor-only

Add ./src/ ./
ENV GOOS darwin
ENV GOARCH amd64
RUN go build -v -o yace-$GOOS-$GOARCH
ENV GOOS linux
ENV GOARCH amd64
ENV CGO_ENABLED=0
RUN go build -v -o yace-$GOOS-$GOARCH

FROM alpine:latest

RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /go/src/yace/yace-linux-amd64 /root
COPY --from=builder /go/src/yace/yace-darwin-amd64 /root

ENTRYPOINT ["/bin/ash", "-c"]
