apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yet-another-cloudwatch-exporter.fullname" . }}
  labels:
    {{- include "yet-another-cloudwatch-exporter.labels" . | nindent 4 }}
data:
  config.yml: |
{{- (tpl .Values.config $) | nindent 4 }}
