apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yet-another-cloudwatch-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "yet-another-cloudwatch-exporter.name" . }}
    helm.sh/chart: {{ include "yet-another-cloudwatch-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.yml: |
{{- (tpl .Values.config $) | nindent 4 }}
