{{- if and (not .Values.aws.role) (not .Values.aws.secret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yet-another-cloudwatch-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "yet-another-cloudwatch-exporter.name" . }}
    helm.sh/chart: {{ include "yet-another-cloudwatch-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.aws.aws_access_key_id }}
  aws_access_key_id: {{ .Values.aws.aws_access_key_id | b64enc | quote }}
  {{ end }}
  {{ if .Values.aws.aws_secret_access_key }}
  aws_secret_access_key: {{ .Values.aws.aws_secret_access_key | b64enc | quote }}
  {{ end }}
{{- end }}
