{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "yet-another-cloudwatch-exporter.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "yet-another-cloudwatch-exporter.name" . }}
    helm.sh/chart: {{ include "yet-another-cloudwatch-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- range $key, $val := .Values.serviceAccount.labels }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
  {{- range $key, $val := .Values.serviceAccount.annotations }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
{{- end }}
